---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      replica: blue
  template:
    metadata:
      labels:
        app: myapp
        replica: blue
    spec:
      containers:
        - name: myapp
          image: philipsinfo/flaskapiant:0.0.5
          resources:
           limits:
            memory: 200Mi
            cpu: 100m
          ports:
            - name: http
              containerPort: 5000
          startupProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 5